name: CI - Build & Test (frontend + backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend - install & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Run backend tests (if none, it safely exits)
        working-directory: backend
        run: npm test || echo "No backend tests found"

  frontend:
    name: Frontend - install & build
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend (Vite)
        working-directory: frontend
        run: npm run build

      - name: Upload frontend build (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
